### ISSUE TITLE
I start the live-server in a folder, open a html, make a change.

### ISSUE THREAD

**Issue by tik9** [tapio/live-server#359]
## Issue description
I start the live-server in a folder, open a html, make a change. No change in the browser, but on cmd: Change detected C:\Users\User\documents\te.html
## Software details

* Command line used for launching `live-server`: powershell
* OS: Win 10
* Browser (if browser related): chrome
* Node.js version:6.14
* `live-server` version:1.2.1

**Comment by gmoqa** [comment]
**Same here** 

OS: Linux Manjaro
Browser : Firefox
npm version: 6.14
live-server version : 1.2.1

**Comment by ArtskydJ** [comment]
I had this issue, and fixed it by adding a `</head>` or `</body>` tag in my HTML.
https://github.com/tapio/live-server/blob/master/index.js#L45

**Comment by gmoqa** [comment]
fixed, just update

**Comment by tik9** [comment]
@gmoqa how did you fix?

**Comment by Ajith-stark** [comment]
> @gmoqa how did you fix?

`sudo npm i live-server -g` this will update.

**Comment by reyronald** [comment]
This is still happening in the latest version (`1.2.1` at the monent). Live reload won't work unless there's a tag in the HTML the script can be injected on (`body`, `head`, and `svg`).

Ideally this could work regardless. Is there a reason why the library can't create any of those tags if they don't exist ?

**Comment by beetle442002** [comment]
Just as a reference this applies seems to apply to the atom-live-server https://github.com/jas-chen/atom-live-server
